# Generated by Django 4.0.5 on 2022-07-30 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.TextField(blank=True, max_length=50)),
                ('status', models.TextField(blank=True, max_length=300)),
                ('pic', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
